 
CREATE TABLE IF NOT EXISTS bf_pipelines (
   	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	name VARCHAR(255) NOT NULL,
	cron_expression VARCHAR(100) NOT NULL,
	description text NULL,
	blocked bool NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
	CONSTRAINT pk_pipelines PRIMARY KEY (id) 
);      

CREATE UNIQUE INDEX ux_bf_pipelines_name ON bf_pipelines (name);

CREATE TABLE IF NOT EXISTS bf_pipeline_items (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	pipeline_id int8 NOT NULL,
	type_operation_id VARCHAR(255) NOT NULL,
	sort_order int4 NOT NULL,
	description text NULL,
	blocked bool NOT NULL,
	options jsonb NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_pipeline_items PRIMARY KEY (id)
);

CREATE INDEX ix_bf_pipeline_items_pipeline_id ON bf_pipeline_items USING btree (pipeline_id);

ALTER TABLE bf_pipeline_items ADD CONSTRAINT fk_pipeline_items_pipelines_pipeline_id FOREIGN KEY (pipeline_id) REFERENCES bf_pipelines(id) ON DELETE CASCADE;

CREATE INDEX bf_pipeline_items_sort_order_idx ON bf_pipeline_items (pipeline_id, sort_order);