

CREATE TABLE public.bf_pipelines (
  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
  "name" varchar(255) NOT NULL,
  cron_expression varchar(100) NOT NULL,
  description text NULL,
  "blocked" bool NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by varchar(100) NULL,
  updated_by varchar(100) NULL,
  CONSTRAINT pk_pipelines PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ux_bf_pipelines_name ON public.bf_pipelines USING btree (name);



CREATE TABLE public.bf_pipeline_items (
  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
  pipeline_id int8 NOT NULL,
  type_operation_id varchar(255) NOT NULL,
  sort_order int4 NOT NULL,
  description text NULL,
  "blocked" bool NOT NULL,
  "options" jsonb NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_pipeline_items PRIMARY KEY (id)
);
CREATE INDEX ix_bf_pipeline_items_pipeline_id ON public.bf_pipeline_items USING btree (pipeline_id);
CREATE INDEX bf_pipeline_items_sort_order_idx ON public.bf_pipeline_items USING btree (pipeline_id, sort_order);
ALTER TABLE public.bf_pipeline_items ADD CONSTRAINT fk_pipeline_items_pipelines_pipeline_id FOREIGN KEY (pipeline_id) REFERENCES public.bf_pipelines(id) ON DELETE CASCADE;



CREATE TABLE public.bf_journal (
  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
  "period" timestamp NOT NULL,
  pipeline_name text NOT NULL,
  item_description text NOT NULL,
  item_sort_order int4 NOT NULL,
  type_action text NOT NULL,
  type_operation_id text NOT NULL,
  launch_id text NOT NULL,
  message text NOT NULL,
  "trigger" text NOT NULL,
  is_start_now bool DEFAULT false NOT NULL,
  item_id int8 DEFAULT 0 NOT NULL,
  CONSTRAINT pk_bf_journal PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS bf_cancellation_requests (
	id int8,
	pipeline_name text NOT NULL,
	expiration_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	description text NULL,
	closing_by_expiration_time_only bool DEFAULT false NOT NULL,
	created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	executed bool DEFAULT false NOT NULL,
	closing_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	closed_after_expiration_date bool DEFAULT false NOT NULL,
	CONSTRAINT pk_bf_cancellation_requests PRIMARY KEY (id)
);